name: Daily Python Parser

on:
  schedule:
    - cron: '0 0 * * *'  # Запускать скрипт ежедневно в полночь
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  run-parser:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'  # Укажите версию Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager beautifulsoup4 pandas openpyxl lxml pytz

    - name: Run Python script
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  # Используйте ваш токен здесь
      run: python your_script.py  # Укажите имя вашего скрипта

    - name: Commit and push changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add downloads/parsed_data.xlsx
        git commit -m "Update parsed_data.xlsx with new data" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main || echo "No changes to push"
