name: Timer Workflow

on:
  workflow_dispatch:

jobs:
  wait-and-restart:
    runs-on: ubuntu-latest

    steps:
    - name: Wait for 55 seconds
      run: |
        echo "Starting timer for 18000 seconds..."
        sleep 18000  # Задержка на 5 часов

    - name: Restart Bot Workflow
      run: |
        echo "Restarting Bot Workflow..."
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/main.yml/dispatches \
          -d '{"ref":"main"}'
